data:
  images_path: "/scratch/hk3820/capstone/data/paco_frames/v1/paco_frames"
  annotations_file: "/scratch/hk3820/capstone/data/paco_annotations/paco_ego4d_v1_train.json"
  num_train_images: 2500 # Keep high enough to ensure that at least one of each label is seen in training. 2500 is a good minimum
  num_test_images: 100

training:
  n_epochs: 12
  learning_rate: 5e-5  # Keep very low
  train_batch_size: 8
  save_eval_images: false
  use_class_weight: true 
  weight_decay: 0.1  # default
  confidence_threshold: 0.01  # This can be quite low and still achieve good results
  iou_threshold: 0.45  # For nms
  owl_vit_checkpoint: "google/owlvit-base-patch32"
  model_checkpoint_path: "./checkpoints"
  num_pos_queries: 1
  num_neg_queries: 3
  # NOTE: Use these values for benchmarking to stay consistent with YOLO, fasterRCNN, SSD, DETR,... etc
  #   confidence_threshold: 0.01  
  #   iou_threshold: 0.45


  
